version: 2.1
jobs:
  build:
    working_directory: ~/totoro/webapp
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm ci     
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            -  ~/totoro/webapp/build
      - run:
          name: Deploy to Netlify
          command:  ~/totoro/webapp/node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
  version: 2
  build-deploy2:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main