version: 2.1
jobs:
  build:
    working_directory: ~/totoro/webapp
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout:
          path: ~/totoro
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps   
      - run:
          name: Build React App
          command: CI=false npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            -  build
      - run:
          name: Deploy to Netlify
          command: cat package.json
workflows:
  version: 2
  build-deploy3:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main